package com.mihail.pgn;

/* Generated By:JavaCC: Do not edit this line. PGNParserConstants.java */
public interface PGNParserConstants {

	int EOF = 0;

	int LBRACKET = 3;

	int LPAREN = 4;

	int RPAREN = 5;

	int RBRACE = 6;

	int LBRACE = 7;

	int DOT = 8;

	int MOVE_NUMBER = 9;

	int BLACK_MOVE = 10;

	int FILE_NAME = 11;

	int RANK_NAME = 12;

	int SQUARE = 13;

	int CASTLE_KINGSIDE = 14;

	int CASTLE_QUEENSIDE = 15;

	int PIECE_IDENT = 16;

	int PROMOTE = 17;

	int CAPTURE = 18;

	int DASH = 19;

	int CHECK = 20;

	int END_OF_TOKEN = 21;

	int EOL = 22;

	int CHECKMATE = 23;

	int SUFFIX_ANNOTATION = 24;

	int NAG = 25;

	int INTEGER = 26;

	int DIGIT = 27;

	int LETTER = 28;

	int GAME_TERMINATOR = 29;

	int RBRACKET = 30;

	int SPACE = 31;

	int SYMBOL = 32;

	int STRING = 33;

	int LAZYSTRING = 34;

	int START_OF_COMMENT = 35;

	int COMMENT = 37;

	int MOVE_COMMENT = 39;

	int IN_MOVE_COMMENT = 0;

	int DEFAULT = 1;

	int IN_PGN_TAG = 2;

	int IN_COMMENT = 3;

	String[] tokenImage = { "<EOF>", "\"\\r\"", "\"\\n\"", "\"[\"", "\"(\"",
			"\")\"", "\"}\"", "\"{\"", "\".\"", "<MOVE_NUMBER>",
			"<BLACK_MOVE>", "<FILE_NAME>", "<RANK_NAME>", "<SQUARE>",
			"<CASTLE_KINGSIDE>", "<CASTLE_QUEENSIDE>", "<PIECE_IDENT>",
			"\"=\"", "\"x\"", "\"-\"", "\"+\"", "<END_OF_TOKEN>", "<EOL>",
			"<CHECKMATE>", "<SUFFIX_ANNOTATION>", "<NAG>", "<INTEGER>",
			"<DIGIT>", "<LETTER>", "<GAME_TERMINATOR>", "\"]\"", "\" \"",
			"<SYMBOL>", "<STRING>", "<LAZYSTRING>", "<START_OF_COMMENT>",
			"<token of kind 36>", "<COMMENT>", "<token of kind 38>",
			"<MOVE_COMMENT>", };

}
